name: Download daily NASDAQ dump

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download NASDAQ stock data
        run: |
          wget --header="Accept: */*" --header="Accept-Encoding: *" --header="User-Agent: Mozilla" "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=20000" -O /tmp/nasdaq_stocks.json
          jq '.data.table.rows' /tmp/nasdaq_stocks.json > data/nasdaq_stocks.json

      - name: Push to repository
        run: |
          git config --global user.name "Pilate"
          now=$(date)
          git add -A
          git commit -m "Auto update on $now"
          git push