name: Download daily NASDAQ dump

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Modify date and time
        run: |
          wget --header="Accept: */*" --header="Accept-Encoding: *" --header="User-Agent: Mozilla" "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=20000" -O data/stocks.json
      - name: Push to repository
        run: |
          git config --global user.name "Pilate"
          now=$(date)
          git add -A
          git commit -m "Auto update on $now"
          git push